---

- id: generic-trailing-whitespaces
  name: '[Generic] Remove trailing whitespaces'
  description: >
    Remove trailing whitespaces from all files.
  language: system
  files: .*
  types: [text]
  entry: sed --in-place 's/[[:space:]]\+$//'

- id: generic-non-breaking-spaces
  name: '[Generic] Remove nbsp characters'
  description: >
    Remove non-breaking spaces from all text files.
  language: system
  files: .*
  types: [text]
  entry: sed --in-place 's/\xC2\xA0/ /g'

- id: generic-check-for-binary-files
  name: '[Generic] Check for binary files'
  description: >
    Detect binary files being commited.
  language: python
  files: .*
  types: [file]
  entry: generic-check-for-binary-files

- id: generic-fix-end-of-files
  name: '[Generic] Fix end of files'
  description: >
    Delete empty lines at the end of files.
  language: python
  files: .*
  types: [text]
  entry: generic-fix-end-of-files

- id: generic-replace-tabs-with-spaces
  name: '[Generic] Replace tabs with spaces'
  description: >
    Find tabs and replace them with spaces.
  language: python
  files: .*
  types: [text]
  entry: generic-replace-tabs-with-spaces

- id: terraform-format
  name: '[TF] Terraform formatter'
  description: Run terraform fmt against .tf files.
  language: system
  files: (\.tf)$
  types: [file]
  entry: terraform fmt -recursive
