---

- id: generic-trailing-whitespaces
  name: '[Generic] Remove trailing whitespaces'
  description: >
    Remove trailing whitespaces from all text files.
  language: system
  files: .*
  types: [text]
  entry: sed --in-place 's/[[:space:]]\+$//'

- id: generic-non-breaking-spaces
  name: '[Generic] Remove nbsp characters'
  description: >
    Remove non-breaking spaces from all text files.
  language: system
  files: .*
  types: [text]
  entry: sed --in-place 's/\xC2\xA0/ /g'

- id: generic-check-for-binary-files
  name: '[Generic] Check for binary files'
  description: >
    Detect binary files being commited.
  language: python
  files: .*
  types: [file]
  entry: generic-check-for-binary-files

- id: generic-fix-end-of-files
  name: '[Generic] Fix end of files'
  description: >
    Delete empty lines at the end of files.
  language: python
  files: .*
  types: [text]
  entry: generic-fix-end-of-files

- id: generic-replace-tabs-with-spaces
  name: '[Generic] Replace tabs with spaces'
  description: >
    Find tabs and replace them with spaces.
  language: python
  files: .*
  types: [text]
  entry: generic-replace-tabs-with-spaces

- id: python-ruff-linter
  name: '[Python] Run ruff check'
  description: >
    Run the ruff linter.
  language: python
  additional_dependencies:
    - ruff
  types:
    - python
  require_serial: true
  entry: ruff check
  args:
    - --force-exclude
    - --fix
    - --show-fixes
    - --no-unsafe-fixes

- id: python-ruff-formatter
  name: '[Python] Run ruff format'
  description: >
    Run the ruff formatter.
  language: python
  additional_dependencies:
    - ruff
  types:
    - python
  require_serial: true
  entry: ruff format
  args:
    - --force-exclude
    - --line-length=100

- id: terraform-format
  name: '[TF] Terraform formatter'
  description: Run terraform fmt against .tf files.
  language: python
  files: (\.tf)$
  types: [file]
  entry: terraform-format

- id: packer-format
  name: '[HCL] Packer formatter'
  description: Run packer fmt command against packer files.
  language: python
  files: \.(pkr\.hcl|pkrvars\.hcl)$
  types: [file]
  entry: packer-format
