---
repos:
- repo: https://github.com/clemfou/PreCommitHooks
  rev: vA.B.C # Tag or commit you want to point at
  hooks:
    # Delete checks you're not interested in
    - id: generic-check-for-binary-files
    - id: generic-fix-end-of-files
    - id: generic-non-breaking-spaces
    - id: generic-replace-tabs-with-spaces
      args: [--shiftwidth=8]
    - id: generic-trailing-whitespaces
    - id: python-ruff-linter
    - id: python-ruff-formatter
    - id: terraform-format
